Organizations:
  - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/orderer.com/msp
      Policies:
        Readers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
        Writers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
        Admins:
            Type: Signature
            Rule: "OR('OrdererMSP.admin')"

  - &Org1
      Name: Org1
      ID: Org1MSP
      MSPDir: crypto-config/peerOrganizations/org1.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('Org1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Org1MSP.peer')"
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true
Channel: &ChannelConf
  Capabilities: *ChannelCapabilities
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
Application: &ApplicationConf
  Capabilities: *ApplicationCapabilities
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    LifecycleEndorsement:
        Type: ImplicitMeta
        Rule: "MAJORITY Endorsement"
    Endorsement:
        Type: ImplicitMeta
        Rule: "MAJORITY Endorsement" # only org1 need to approve chaincode
Orderer: &OrdererConf
  Capabilities: *OrdererCapabilities
  OrdererType: solo
  Addresses:
    - orderer:7050
  Policies:
      Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
      Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
      Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"
Profiles:
  Genesis:
    <<: *ChannelConf
    Orderer:
      <<: *OrdererConf
      Organizations:
        - *OrdererOrg
    Consortiums:
        DevConsortium:
            Organizations:
                - *Org1
  DevChannel:
    <<: *ChannelConf
    Consortium: DevConsortium   
    Application:
      <<: *ApplicationConf
      Organizations:
        - *Org1
