OrdererOrgs:
  - Name: OrdererOrg
    Domain: orderer.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        CommonName: "{{.Hostname}}"
PeerOrgs:
  - Name: Org1
    Domain: org1.com
    EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: "{{.Hostname}}"
      